version = 1

[project]
name = "Trebble Demo"
region = "us-east-01"

[[frames]]
name = "trebble-dashboard"
stack = "sveltekit"
port = 3000
replicas = 1

[[frames]]
name = "trebble-db"
kind = "database"
engine = "mongodb"
storage_gb = 1
inject_into = "trebble-dashboard"
inject_as = "DATABASE_URL"

[deploy]
prune = false
preview_deploys = false
